version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "@stellar/stellar-sdk"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@allbridge/bridge-core-sdk"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
